<?php
/**
 * Title: Directory section 4 - micro, three columns
 * Slug: pitchfork/directory-micro-three-col
 * Categories: pitchfork-directory
 * Block Types: core
 */
?>

<!-- wp:heading -->
<h2>Down to the <span class="highlight-gold">micro profile size.</span> </h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead"} -->
<p class="is-style-lead"><strong>These blocks have no default profile image. Be sure to upload your own image in the block settings.</strong><br>The micro size works really well on mobile for when you have a lot of people within one section on the page.</p>
<!-- /wp:paragraph -->

<!-- wp:acf/profiles {"name":"acf/profiles","data":{"field_63c98c07e138e":"col-three"},"mode":"preview","style":{"spacing":{"margin":{"top":"var:preset|spacing|uds-size-6","bottom":"var:preset|spacing|uds-size-6"}}}} -->
<!-- wp:acf/profile-manual {"name":"acf/profile-manual","data":{"uds_profilemanual_name":"Default Name","_uds_profilemanual_name":"field_63bf28de08674","uds_profilemanual_image":"","_uds_profilemanual_image":"field_63bf2b7c0aec6","uds_profilemanual_url":"https://search.asu.edu","_uds_profilemanual_url":"field_63bf2e0a0aec8","uds_profilemanual_title":"Trusted Faculty","_uds_profilemanual_title":"field_63bf295b0aec1","uds_profilemanual_department":"ASU Engineering","_uds_profilemanual_department":"field_63bf298c0aec2","uds_profilemanual_description":"ASU is a comprehensive public research university, measured not by whom it excludes, but by whom it includes and how they succeed; advancing research and discovery of public value; and assuming fundamental responsibility for the economic, social, cultural and overall health of the communities it serves.","_uds_profilemanual_description":"field_63bf2c770aec7","uds_profilemanual_email":"email@asu.edu","_uds_profilemanual_email":"field_63bf299a0aec3","uds_profilemanual_phone":"480-123-4567","_uds_profilemanual_phone":"field_63bf2a420aec4","uds_profilemanual_address":"","_uds_profilemanual_address":"field_63bf2b400aec5","uds_profilemanual_social":"","_uds_profilemanual_social":"field_63c82588b90ee"},"mode":"preview","className":"is-style-micro","backgroundColor":"fill"} /-->
<!-- wp:acf/profile-manual {"name":"acf/profile-manual","data":{"uds_profilemanual_name":"Default Name","_uds_profilemanual_name":"field_63bf28de08674","uds_profilemanual_image":"","_uds_profilemanual_image":"field_63bf2b7c0aec6","uds_profilemanual_url":"https://search.asu.edu","_uds_profilemanual_url":"field_63bf2e0a0aec8","uds_profilemanual_title":"Trusted Faculty","_uds_profilemanual_title":"field_63bf295b0aec1","uds_profilemanual_department":"ASU Engineering","_uds_profilemanual_department":"field_63bf298c0aec2","uds_profilemanual_description":"ASU is a comprehensive public research university, measured not by whom it excludes, but by whom it includes and how they succeed; advancing research and discovery of public value; and assuming fundamental responsibility for the economic, social, cultural and overall health of the communities it serves.","_uds_profilemanual_description":"field_63bf2c770aec7","uds_profilemanual_email":"email@asu.edu","_uds_profilemanual_email":"field_63bf299a0aec3","uds_profilemanual_phone":"480-123-4567","_uds_profilemanual_phone":"field_63bf2a420aec4","uds_profilemanual_address":"","_uds_profilemanual_address":"field_63bf2b400aec5","uds_profilemanual_social":"","_uds_profilemanual_social":"field_63c82588b90ee"},"mode":"preview","className":"is-style-micro","backgroundColor":"fill"} /-->
<!-- wp:acf/profile-manual {"name":"acf/profile-manual","data":{"uds_profilemanual_name":"Default Name","_uds_profilemanual_name":"field_63bf28de08674","uds_profilemanual_image":"","_uds_profilemanual_image":"field_63bf2b7c0aec6","uds_profilemanual_url":"https://search.asu.edu","_uds_profilemanual_url":"field_63bf2e0a0aec8","uds_profilemanual_title":"Trusted Faculty","_uds_profilemanual_title":"field_63bf295b0aec1","uds_profilemanual_department":"ASU Engineering","_uds_profilemanual_department":"field_63bf298c0aec2","uds_profilemanual_description":"ASU is a comprehensive public research university, measured not by whom it excludes, but by whom it includes and how they succeed; advancing research and discovery of public value; and assuming fundamental responsibility for the economic, social, cultural and overall health of the communities it serves.","_uds_profilemanual_description":"field_63bf2c770aec7","uds_profilemanual_email":"email@asu.edu","_uds_profilemanual_email":"field_63bf299a0aec3","uds_profilemanual_phone":"480-123-4567","_uds_profilemanual_phone":"field_63bf2a420aec4","uds_profilemanual_address":"","_uds_profilemanual_address":"field_63bf2b400aec5","uds_profilemanual_social":"","_uds_profilemanual_social":"field_63c82588b90ee"},"mode":"preview","className":"is-style-micro","backgroundColor":"fill"} /-->
<!-- wp:acf/profile-manual {"name":"acf/profile-manual","data":{"uds_profilemanual_name":"Default Name","_uds_profilemanual_name":"field_63bf28de08674","uds_profilemanual_image":"","_uds_profilemanual_image":"field_63bf2b7c0aec6","uds_profilemanual_url":"https://search.asu.edu","_uds_profilemanual_url":"field_63bf2e0a0aec8","uds_profilemanual_title":"Trusted Faculty","_uds_profilemanual_title":"field_63bf295b0aec1","uds_profilemanual_department":"ASU Engineering","_uds_profilemanual_department":"field_63bf298c0aec2","uds_profilemanual_description":"ASU is a comprehensive public research university, measured not by whom it excludes, but by whom it includes and how they succeed; advancing research and discovery of public value; and assuming fundamental responsibility for the economic, social, cultural and overall health of the communities it serves.","_uds_profilemanual_description":"field_63bf2c770aec7","uds_profilemanual_email":"email@asu.edu","_uds_profilemanual_email":"field_63bf299a0aec3","uds_profilemanual_phone":"480-123-4567","_uds_profilemanual_phone":"field_63bf2a420aec4","uds_profilemanual_address":"","_uds_profilemanual_address":"field_63bf2b400aec5","uds_profilemanual_social":"","_uds_profilemanual_social":"field_63c82588b90ee"},"mode":"preview","className":"is-style-micro","backgroundColor":"fill-white"} /-->
<!-- wp:acf/profile-manual {"name":"acf/profile-manual","data":{"uds_profilemanual_name":"Default Name","_uds_profilemanual_name":"field_63bf28de08674","uds_profilemanual_image":"","_uds_profilemanual_image":"field_63bf2b7c0aec6","uds_profilemanual_url":"https://search.asu.edu","_uds_profilemanual_url":"field_63bf2e0a0aec8","uds_profilemanual_title":"Trusted Faculty","_uds_profilemanual_title":"field_63bf295b0aec1","uds_profilemanual_department":"ASU Engineering","_uds_profilemanual_department":"field_63bf298c0aec2","uds_profilemanual_description":"ASU is a comprehensive public research university, measured not by whom it excludes, but by whom it includes and how they succeed; advancing research and discovery of public value; and assuming fundamental responsibility for the economic, social, cultural and overall health of the communities it serves.","_uds_profilemanual_description":"field_63bf2c770aec7","uds_profilemanual_email":"email@asu.edu","_uds_profilemanual_email":"field_63bf299a0aec3","uds_profilemanual_phone":"480-123-4567","_uds_profilemanual_phone":"field_63bf2a420aec4","uds_profilemanual_address":"","_uds_profilemanual_address":"field_63bf2b400aec5","uds_profilemanual_social":"","_uds_profilemanual_social":"field_63c82588b90ee"},"mode":"preview","className":"is-style-micro","backgroundColor":"fill-white"} /-->
<!-- wp:acf/profile-manual {"name":"acf/profile-manual","data":{"uds_profilemanual_name":"Default Name","_uds_profilemanual_name":"field_63bf28de08674","uds_profilemanual_image":"","_uds_profilemanual_image":"field_63bf2b7c0aec6","uds_profilemanual_url":"https://search.asu.edu","_uds_profilemanual_url":"field_63bf2e0a0aec8","uds_profilemanual_title":"Trusted Faculty","_uds_profilemanual_title":"field_63bf295b0aec1","uds_profilemanual_department":"ASU Engineering","_uds_profilemanual_department":"field_63bf298c0aec2","uds_profilemanual_description":"ASU is a comprehensive public research university, measured not by whom it excludes, but by whom it includes and how they succeed; advancing research and discovery of public value; and assuming fundamental responsibility for the economic, social, cultural and overall health of the communities it serves.","_uds_profilemanual_description":"field_63bf2c770aec7","uds_profilemanual_email":"email@asu.edu","_uds_profilemanual_email":"field_63bf299a0aec3","uds_profilemanual_phone":"480-123-4567","_uds_profilemanual_phone":"field_63bf2a420aec4","uds_profilemanual_address":"","_uds_profilemanual_address":"field_63bf2b400aec5","uds_profilemanual_social":"","_uds_profilemanual_social":"field_63c82588b90ee"},"mode":"preview","className":"is-style-micro","backgroundColor":"fill-white"} /-->
<!-- /wp:acf/profiles -->
