<?php
/**
 * Title: Directory - Three columns
 * Slug: pitchfork/section-02-directory-3col
 * Categories: pitchfork-section
 * Block Types: core
 */
?>

<!-- wp:heading -->
<h2 class="wp-block-heading">Directory section - three columns, <span class="highlight-gold">micro</span></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead"} -->
<p class="is-style-lead">Documentation for the background treatments and other settings can be found within the <a href="https://comm.engineering.asu.edu/pitchfork/doc-category/pitchfork-people/">plugin documentation</a>.</p>
<!-- /wp:paragraph -->

<!-- wp:acf/profiles {"name":"acf/profiles","data":{"field_63c98c07e138e":"col-three"},"mode":"preview","style":{"spacing":{"margin":{"top":"var:preset|spacing|uds-size-6","bottom":"var:preset|spacing|uds-size-6"}}}} -->
<!-- wp:acf/profile-data {"name":"acf/profile-data","data":{"field_64557ce1fd8cc":"zcholman"},"mode":"preview","className":"is-style-micro"} /-->

<!-- wp:acf/profile-manual {"name":"acf/profile-manual","data":{"uds_profilemanual_name":"Default Name","_uds_profilemanual_name":"field_63bf28de08674","uds_profilemanual_image":"","_uds_profilemanual_image":"field_63bf2b7c0aec6","uds_profilemanual_url":"https://search.asu.edu","_uds_profilemanual_url":"field_63bf2e0a0aec8","uds_profilemanual_title":"Trusted Faculty","_uds_profilemanual_title":"field_63bf295b0aec1","uds_profilemanual_department":"ASU Engineering","_uds_profilemanual_department":"field_63bf298c0aec2","uds_profilemanual_description":"ASU is a comprehensive public research university, measured not by whom it excludes, but by whom it includes and how they succeed; advancing research and discovery of public value; and assuming fundamental responsibility for the economic, social, cultural and overall health of the communities it serves.","_uds_profilemanual_description":"field_63bf2c770aec7","uds_profilemanual_email":"email@asu.edu","_uds_profilemanual_email":"field_63bf299a0aec3","uds_profilemanual_phone":"480-123-4567","_uds_profilemanual_phone":"field_63bf2a420aec4","uds_profilemanual_address":"","_uds_profilemanual_address":"field_63bf2b400aec5","uds_profilemanual_social":"","_uds_profilemanual_social":"field_63c82588b90ee"},"mode":"preview","className":"is-style-micro has-default-img"} /-->

<!-- wp:acf/profile-manual {"name":"acf/profile-manual","data":{"uds_profilemanual_name":"Default Name","_uds_profilemanual_name":"field_63bf28de08674","uds_profilemanual_image":"","_uds_profilemanual_image":"field_63bf2b7c0aec6","uds_profilemanual_url":"https://search.asu.edu","_uds_profilemanual_url":"field_63bf2e0a0aec8","uds_profilemanual_title":"Trusted Faculty","_uds_profilemanual_title":"field_63bf295b0aec1","uds_profilemanual_department":"ASU Engineering","_uds_profilemanual_department":"field_63bf298c0aec2","uds_profilemanual_description":"ASU is a comprehensive public research university, measured not by whom it excludes, but by whom it includes and how they succeed; advancing research and discovery of public value; and assuming fundamental responsibility for the economic, social, cultural and overall health of the communities it serves.","_uds_profilemanual_description":"field_63bf2c770aec7","uds_profilemanual_email":"email@asu.edu","_uds_profilemanual_email":"field_63bf299a0aec3","uds_profilemanual_phone":"480-123-4567","_uds_profilemanual_phone":"field_63bf2a420aec4","uds_profilemanual_address":"","_uds_profilemanual_address":"field_63bf2b400aec5","uds_profilemanual_social":"","_uds_profilemanual_social":"field_63c82588b90ee"},"mode":"preview","className":"is-style-micro"} /-->

<!-- wp:acf/profile-manual {"name":"acf/profile-manual","data":{"uds_profilemanual_name":"Default Name","_uds_profilemanual_name":"field_63bf28de08674","uds_profilemanual_image":"","_uds_profilemanual_image":"field_63bf2b7c0aec6","uds_profilemanual_url":"https://search.asu.edu","_uds_profilemanual_url":"field_63bf2e0a0aec8","uds_profilemanual_title":"Trusted Faculty","_uds_profilemanual_title":"field_63bf295b0aec1","uds_profilemanual_department":"ASU Engineering","_uds_profilemanual_department":"field_63bf298c0aec2","uds_profilemanual_description":"ASU is a comprehensive public research university, measured not by whom it excludes, but by whom it includes and how they succeed; advancing research and discovery of public value; and assuming fundamental responsibility for the economic, social, cultural and overall health of the communities it serves.","_uds_profilemanual_description":"field_63bf2c770aec7","uds_profilemanual_email":"email@asu.edu","_uds_profilemanual_email":"field_63bf299a0aec3","uds_profilemanual_phone":"480-123-4567","_uds_profilemanual_phone":"field_63bf2a420aec4","uds_profilemanual_address":"","_uds_profilemanual_address":"field_63bf2b400aec5","uds_profilemanual_social":"","_uds_profilemanual_social":"field_63c82588b90ee"},"mode":"preview","className":"is-style-micro","backgroundColor":"fill"} /-->

<!-- wp:acf/profile-manual {"name":"acf/profile-manual","data":{"uds_profilemanual_name":"Default Name","_uds_profilemanual_name":"field_63bf28de08674","uds_profilemanual_image":"","_uds_profilemanual_image":"field_63bf2b7c0aec6","uds_profilemanual_url":"https://search.asu.edu","_uds_profilemanual_url":"field_63bf2e0a0aec8","uds_profilemanual_title":"Trusted Faculty","_uds_profilemanual_title":"field_63bf295b0aec1","uds_profilemanual_department":"ASU Engineering","_uds_profilemanual_department":"field_63bf298c0aec2","uds_profilemanual_description":"ASU is a comprehensive public research university, measured not by whom it excludes, but by whom it includes and how they succeed; advancing research and discovery of public value; and assuming fundamental responsibility for the economic, social, cultural and overall health of the communities it serves.","_uds_profilemanual_description":"field_63bf2c770aec7","uds_profilemanual_email":"email@asu.edu","_uds_profilemanual_email":"field_63bf299a0aec3","uds_profilemanual_phone":"480-123-4567","_uds_profilemanual_phone":"field_63bf2a420aec4","uds_profilemanual_address":"","_uds_profilemanual_address":"field_63bf2b400aec5","uds_profilemanual_social":"","_uds_profilemanual_social":"field_63c82588b90ee"},"mode":"preview","className":"is-style-micro","backgroundColor":"fill-white"} /-->
<!-- /wp:acf/profiles -->
